const $=s=>document.querySelector(s);const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));const smooth=(a,b,n)=>{let t=clamp((n-a)/(b-a));return t*t*(3-2*t)};
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');let reduced=motionQuery.matches;
const mobileQuery=matchMedia('(max-width:700px)');
const hero={journey:$('.journey'),stage:$('.hero-stage'),scenery:$('.scenery'),landscape:$('.landscape'),elephant:$('.elephant'),mobile:$('.mobile-scene'),background:$('.mobile-background'),foreground:$('.mobile-foreground'),original:$('.original'),haze:$('.bottom-haze'),bottom:$('.hero-bottom'),shade:$('.hero-shade'),copy:$('.sky-copy'),exit:$('.sky-exit')};
let frame=0,current=0,target=0,lastTime=0;
function progress(){return clamp(-hero.journey.getBoundingClientRect().top/Math.max(1,hero.journey.offsetHeight-hero.stage.offsetHeight))}
function paint(p){
 const zoom=smooth(0,.64,p),exit=smooth(.82,.98,p),mobile=mobileQuery.matches;
 if(mobile){
  hero.scenery.style.transform='none';hero.scenery.style.opacity=1;
  hero.original.style.transform=`translate3d(0,${zoom*18}%,0) scale(${1+zoom*.85})`;
  const ready=hero.mobile.classList.contains('layers-ready');
  hero.original.style.opacity=ready?1-smooth(.005,.045,p):1-smooth(.48,.66,p);
  hero.mobile.style.opacity=ready?1-smooth(.48,.66,p):0;
  hero.background.style.transform=`translate3d(0,${zoom*18}%,0) scale(${1+zoom*.85})`;
  hero.foreground.style.transform=`translate3d(${9.56-zoom*20}%,${9.93+zoom*40}%,0) scale(${.8+zoom*1.16})`;
  hero.foreground.style.opacity=1-smooth(.26,.46,p);
 }else{
  hero.original.style.transform='none';hero.original.style.opacity=1;
  hero.scenery.style.transform=`scale(${1+zoom*1.05}) translateY(${zoom*10}%)`;
  hero.scenery.style.opacity=1-smooth(.48,.66,p);
  const layer=smooth(.05,.14,p);hero.landscape.style.opacity=layer;
  hero.elephant.style.opacity=layer*(1-smooth(.24,.44,p));
  hero.elephant.style.transform=`translateY(${zoom*90}%) scale(${1+zoom*1.5})`;
 }
 hero.haze.style.opacity=1-smooth(0,.16,p);hero.bottom.style.opacity=1-smooth(0,.08,p);hero.bottom.inert=p>.08;
 hero.shade.style.opacity=1-smooth(.25,.6,p);
 hero.copy.style.opacity=smooth(.57,.7,p)*(1-smooth(.80,.90,p));
 hero.copy.style.transform=`scale(${.93+smooth(.57,.7,p)*.07+exit*.08})`;
 hero.copy.style.pointerEvents=p>.6&&p<.83?'auto':'none';hero.copy.inert=!(p>.6&&p<.83);
 hero.exit.style.clipPath=`ellipse(${exit*100}% ${exit*120}% at 50% 100%)`;
 hero.exit.querySelector('img').style.transform=`scale(${1.06-exit*.06})`;
}
function tick(time){frame=0;const dt=Math.min(64,time-(lastTime||time-16));lastTime=time;current+=(target-current)*(1-Math.exp(-dt/75));if(Math.abs(target-current)<.0001)current=target;paint(current);if(current!==target)frame=requestAnimationFrame(tick);else lastTime=0}
function animate(){target=reduced?0:progress();if(reduced){cancelAnimationFrame(frame);frame=0;current=0;paint(0)}else if(!frame)frame=requestAnimationFrame(tick)}
Promise.all([hero.background,hero.foreground].map(img=>img.decode())).then(()=>{hero.mobile.classList.add('layers-ready');animate()}).catch(()=>{});
addEventListener('scroll',animate,{passive:true});addEventListener('resize',animate);motionQuery.addEventListener('change',()=>{reduced=motionQuery.matches;animate()});mobileQuery.addEventListener('change',animate);
let tourResizeTimer;addEventListener('resize',()=>{clearTimeout(tourResizeTimer);tourResizeTimer=setTimeout(setupMobileTourSlider,180)});current=target=reduced?0:progress();paint(current);
$('.menu').addEventListener('click',()=>{const open=$('#nav').classList.toggle('open');$('.menu').setAttribute('aria-expanded',open);$('.menu').setAttribute('aria-label',open?'Close navigation':'Open navigation')});$('#nav').addEventListener('click',()=>{$('#nav').classList.remove('open');$('.menu').setAttribute('aria-expanded','false')});
function setupMobileTourSlider(){const grid=$('#tour-grid');grid.querySelectorAll('[data-mobile-clone]').forEach(card=>card.remove());grid.classList.remove('mobile-slider');if(innerWidth>700||reduced||grid.children.length<2)return;[...grid.children].forEach(card=>{const clone=card.cloneNode(true);clone.dataset.mobileClone='true';clone.setAttribute('aria-hidden','true');clone.inert=true;grid.append(clone)});grid.classList.add('mobile-slider')}
const tours=[{days:4,title:'Sigiriya Tour',name:'4-Day Sigiriya Tour',image:'itinerary/sigiriya.webp',page:'tours/4-day-sigiriya.html',tag:'ANCIENT WONDERS & WILDLIFE',description:'Rock fortresses, village life, an ancient capital and an elephant safari in four memorable days.',route:'Dambulla · Sigiriya · Polonnaruwa · Pidurangala',interests:['culture','nature']},{days:7,title:'Sri Lanka Journey',name:'7-Day Sri Lanka Journey',image:'itinerary/arugam-bay.webp',page:'tours/7-day-sri-lanka.html',tag:'ROCKS, HILLS & SOUTHERN SHORES',description:'Travel from Sigiriya and Ella to the surf coast and the quiet beaches of Tangalle.',route:'Sigiriya · Ella · Arugam Bay · Tangalle',interests:['culture','nature','coast']},{days:10,title:'South Coast & Ella',name:'10-Day South Coast & Ella',image:'itinerary/bentota.webp',page:'tours/10-day-south-coast-ella.html',tag:'COASTAL DAYS & HILL-COUNTRY VIEWS',description:'Follow the southern coastline, turn into tea country and finish with a wildlife safari.',route:'Colombo · Galle · Mirissa · Ella · Udawalawe',interests:['nature','coast']},{days:15,title:'Grand Sri Lanka',name:'15-Day Grand Sri Lanka',image:'itinerary/nallur-temple.webp',page:'tours/15-day-grand-sri-lanka.html',tag:'THE ISLAND, FROM NORTH TO SOUTH',description:'A wide-ranging journey through northern heritage, eastern beaches, ancient cities and Kandy.',route:'Negombo · Jaffna · Trincomalee · Sigiriya · Kandy',interests:['culture','nature','coast']}];
function filterTours(duration='all',interest='all',scroll=true){const found=tours.filter(t=>(duration==='all'||t.days===Number(duration))&&(interest==='all'||t.interests.includes(interest)));$('#duration').value=duration;$('#interest').value=interest;$('#tour-grid').innerHTML=found.length?found.map(t=>`<article class="tour-card"><div class="tour-image"><img src="assets/${t.image}" loading="lazy" alt="Sri Lanka scenery for the ${t.days}-day ${t.title} journey"><span class="duration-badge">${t.days} days / ${t.days-1} nights</span></div><div class="tour-body"><span class="eyebrow">${t.tag}</span><h3>${t.title}</h3><p>${t.description}</p><p class="tour-route">${t.route}</p><a class="journey-link" href="${t.page}">Select this journey <span>↗</span></a></div></article>`).join(''):'<div class="empty-results"><h3>A journey made for you.</h3><p>No journey matches both choices. Try another duration or tell us what you have in mind.</p><a class="button outline" href="#inquiry" style="margin-top:20px">Plan a custom journey ↗</a></div>';setupMobileTourSlider();$('#results').textContent=duration==='all'&&interest==='all'?'Four ways to discover Sri Lanka':`${found.length} ${found.length===1?'journey matches':'journeys match'} your preferences`;if(scroll)$('#tours').scrollIntoView({behavior:reduced?'instant':'smooth'});return found.map(t=>({days:t.days,name:t.name,details:t.page}))}
$('#finder').addEventListener('submit',e=>{e.preventDefault();filterTours($('#duration').value,$('#interest').value)});$('#reset-tours').addEventListener('click',()=>filterTours());function chooseJourney(name){$('#inquiry-tour').value=name;$('#selected-journey').textContent=`Your choice: ${name}`;$('#selected-journey').hidden=false;$('#inquiry').scrollIntoView({behavior:reduced?'instant':'smooth'})}document.querySelectorAll('[data-interest]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();filterTours('all',a.dataset.interest)}));document.querySelectorAll('[data-vehicle]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();chooseJourney(a.dataset.vehicle)}));filterTours('all','all',false);const requestedTour=new URLSearchParams(location.search).get('tour');if(requestedTour&&[...$('#inquiry-tour').options].some(o=>o.value===requestedTour)){ $('#inquiry-tour').value=requestedTour;$('#selected-journey').textContent=`Your choice: ${requestedTour}`;$('#selected-journey').hidden=false}$('#inquiry-tour').addEventListener('change',()=>{$('#selected-journey').textContent=`Your choice: ${$('#inquiry-tour').value}`;$('#selected-journey').hidden=false});$('#year').textContent=new Date().getFullYear();const dateInput=$('[name="date"]');const today=new Date();dateInput.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
let inquiryText='';$('#inquiry-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);inquiryText=`ANDRIANA TOURS — TRIP INQUIRY\n\nName: ${f.get('name')}\nEmail: ${f.get('email')}\nPreferred date: ${f.get('date')||'Flexible'}\nTravellers: ${f.get('travellers')}\nJourney: ${f.get('tour')}\n\nTrip notes:\n${f.get('message')||'Not provided'}\n\nThis is a trip inquiry and not a confirmed booking.`;$('#inquiry-preview').textContent=inquiryText;const subject=encodeURIComponent(`Sri Lanka trip inquiry — ${f.get('tour')}`);$('#email-inquiry').href=`mailto:andrianatours@gmail.com?subject=${subject}&body=${encodeURIComponent(inquiryText)}`;$('#inquiry-dialog').showModal()});$('#email-inquiry').addEventListener('click',()=>{$('#form-status').textContent='Your email app is opening with the inquiry addressed to Andriana Tours.'});$('#download-inquiry').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([inquiryText],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='andriana-tours-inquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#form-status').textContent='Your inquiry copy is ready.'});document.querySelectorAll('.dialog-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));$('#credits-button').addEventListener('click',()=>$('#credits-dialog').showModal());
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'filter_tour_ideas',title:'Find a Sri Lanka tour idea',description:'Filter the visible sample tour cards by duration and interest. Does not book or send an inquiry.',inputSchema:{type:'object',properties:{duration:{type:'string',enum:['all','4','7','10','15']},interest:{type:'string',enum:['all','culture','nature','coast']}},required:['duration','interest'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!['all','4','7','10','15'].includes(input.duration)||!['all','culture','nature','coast'].includes(input.interest))throw new Error('Choose a supported duration and interest.');return{tours:filterTours(input.duration,input.interest)}}})}catch(e){console.info('Optional tour tool unavailable.')}}

function startCarousel(root){const group=root.querySelector('.carousel-group');if(!group.children.length)return;const duplicate=group.cloneNode(true);duplicate.setAttribute('aria-hidden','true');duplicate.inert=true;duplicate.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));root.querySelector('.carousel-track').append(duplicate);root.querySelector('.carousel-toggle').addEventListener('click',e=>{const paused=root.classList.toggle('paused');e.currentTarget.textContent=paused?'Resume movement':'Pause movement';e.currentTarget.setAttribute('aria-pressed',String(paused))});}
startCarousel(document.querySelector('#vehicle-carousel'));
startCarousel(document.querySelector('#memory-reel'));
fetch('reviews.json').then(r=>{if(!r.ok)throw new Error('Reviews unavailable');return r.json()}).then(reviews=>{const root=document.querySelector('#reviews-carousel'),group=root.querySelector('.review-group');reviews.filter(r=>typeof r.text==='string'&&r.text.trim()&&typeof r.author==='string').forEach(r=>{const card=document.createElement('article');card.className='review-card';const quote=document.createElement('blockquote');quote.textContent=r.text;const author=document.createElement('p');author.textContent=r.author;card.append(quote,author);group.append(card)});if(group.children.length){root.hidden=false;startCarousel(root)}}).catch(()=>{});
